/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SI;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;   
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tentangmac
 */
public class formDataKaryawan extends javax.swing.JFrame {
    
    /**
     * Creates new form formDataKaryawan
     */
    public Statement st;
    public ResultSet rs;
    Connection con = koneksi.db_karyawan.konek();
    
    public formDataKaryawan() {
        initComponents();
        tampilData();
        autoNumber();
        tSize();
    }
    
    private void bersih(){
        txtId.setText("");
        txtNama.setText("");
        bagian.setSelectedItem("Staff");
        txtNotelp.setText("");
        txtAlamat.setText("");
        
        tSize();

        simpan.setText("SIMPAN");
        txtId.setEditable(true);
    }
    private void cariData(){
        try {
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM karyawan WHERE "+ cari.getSelectedItem().toString() + " LIKE '%"+ txtCari.getText() +"%'");
            
            DefaultTableModel mdl = new DefaultTableModel();
            
            mdl.addColumn("No");
            mdl.addColumn("ID");
            mdl.addColumn("Nama");
            mdl.addColumn("Bagian");
            mdl.addColumn("No Telp");
            mdl.addColumn("JK");
            mdl.addColumn("Tgl Masuk");
            mdl.addColumn("Alamat");
                    
            mdl.getDataVector().removeAllElements();
            mdl.fireTableDataChanged();
            mdl.setRowCount(0);
            
            
            
            int no = 1;
            while (rs.next()) {
                Object[] data = {
                    no++,
                    rs.getString("Id"),
                    rs.getString("nama"),
                    rs.getString("bagian"),
                    rs.getString("telepon"),
                    rs.getString("JK"),
                    rs.getString("tgl_msk"),
                    rs.getString("alamat")
                };
                mdl.addRow(data);
                tabelKry.setModel(mdl);
            }
        } catch (Exception e) {
            
        }
    }
    private void tampilData(){
        try {
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM karyawan ORDER BY Id DESC");
        
            DefaultTableModel mdl = new DefaultTableModel();
            
            mdl.addColumn("No");
            mdl.addColumn("ID");
            mdl.addColumn("Nama");
            mdl.addColumn("Bagian");
            mdl.addColumn("No Telp");
            mdl.addColumn("JK");
            mdl.addColumn("Tgl Masuk");
            mdl.addColumn("Alamat");
                    
            mdl.getDataVector().removeAllElements();
            mdl.fireTableDataChanged();
            mdl.setRowCount(0);
            
            
            
            int no = 1;
            while (rs.next()) {
                Object[] data = {
                    no++,
                    rs.getString("Id"),
                    rs.getString("nama"),
                    rs.getString("bagian"),
                    rs.getString("telepon"),
                    rs.getString("JK"),
                    rs.getString("tgl_msk"),
                    rs.getString("alamat")
                };
                mdl.addRow(data);
                tabelKry.setModel(mdl);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        tSize();
    }
    private void tSize() {
        tabelKry.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabelKry.getColumnModel().getColumn(1).setPreferredWidth(40);
        tabelKry.getColumnModel().getColumn(2).setPreferredWidth(140);
        tabelKry.getColumnModel().getColumn(3).setPreferredWidth(60);
        tabelKry.getColumnModel().getColumn(4).setPreferredWidth(50);
        tabelKry.getColumnModel().getColumn(5).setPreferredWidth(50);
        tabelKry.getColumnModel().getColumn(6).setPreferredWidth(60);
        tabelKry.getColumnModel().getColumn(7).setPreferredWidth(70);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new cambodia.raven.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNotelp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtTgl = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jk = new javax.swing.JComboBox<>();
        btnTgl = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        bagian = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKry = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        hapus1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();

        dateChooser1.setButton(btnTgl);
        dateChooser1.setTextRefernce(txtTgl);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(75, 86, 210));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DATA KARYAWAN");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-data-sheet-60.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("x");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/left.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("back");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addContainerGap(487, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel14))
                    .addComponent(jLabel13))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 86, 210), 2));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 86, 210));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(75, 86, 210));
        jLabel3.setText("Nama");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 86, 210));
        jLabel5.setText("No Telp");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(75, 86, 210));
        jLabel6.setText("Alamat");

        jPanel4.setBackground(new java.awt.Color(75, 86, 210));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 86, 210), 2));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INPUT DATA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel4)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        txtId.setForeground(new java.awt.Color(75, 86, 210));
        txtId.setBorder(null);

        txtNama.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        txtNama.setForeground(new java.awt.Color(75, 86, 210));
        txtNama.setBorder(null);

        txtNotelp.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        txtNotelp.setForeground(new java.awt.Color(75, 86, 210));
        txtNotelp.setBorder(null);

        jScrollPane2.setBorder(null);

        txtAlamat.setColumns(20);
        txtAlamat.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(75, 86, 210));
        txtAlamat.setRows(5);
        txtAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 86, 210)));
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlamatKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtAlamat);

        txtTgl.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        txtTgl.setForeground(new java.awt.Color(75, 86, 210));
        txtTgl.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(75, 86, 210));
        jLabel8.setText("Jenis Kelamin");

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(75, 86, 210));
        jLabel9.setText("Tanggal Masuk");

        jk.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jk.setForeground(new java.awt.Color(75, 86, 210));
        jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        jk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnTgl.setBackground(new java.awt.Color(75, 86, 210));
        btnTgl.setForeground(new java.awt.Color(75, 86, 210));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(75, 86, 210));
        jLabel10.setText("Bagian");

        bagian.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        bagian.setForeground(new java.awt.Color(75, 86, 210));
        bagian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Kasir", "Admin", "Asisten Manager", "Manager", " ", " " }));
        bagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagianActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(75, 86, 210));

        jSeparator3.setForeground(new java.awt.Color(75, 86, 210));

        jSeparator1.setForeground(new java.awt.Color(75, 86, 210));

        jSeparator4.setForeground(new java.awt.Color(75, 86, 210));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTgl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bagian, 0, 218, Short.MAX_VALUE))
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNotelp)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(bagian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtNotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jScrollPane1.setBorder(null);

        tabelKry.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        tabelKry.setForeground(new java.awt.Color(75, 86, 210));
        tabelKry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID", "Nama", "Bagian", "No Telp", "JK", "Tgl Masuk", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelKry.setRowHeight(30);
        tabelKry.setSelectionBackground(new java.awt.Color(75, 86, 210));
        tabelKry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKry);

        simpan.setBackground(new java.awt.Color(75, 86, 210));
        simpan.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        simpan.setForeground(new java.awt.Color(241, 246, 245));
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(75, 86, 210));
        hapus.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        hapus.setForeground(new java.awt.Color(241, 246, 245));
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        batal.setBackground(new java.awt.Color(75, 86, 210));
        batal.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        batal.setForeground(new java.awt.Color(241, 246, 245));
        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(75, 86, 210));
        jLabel7.setText("Cari Data");

        cari.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        cari.setForeground(new java.awt.Color(75, 86, 210));
        cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nama" }));

        txtCari.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        txtCari.setForeground(new java.awt.Color(75, 86, 210));
        txtCari.setBorder(null);
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        hapus1.setBackground(new java.awt.Color(75, 86, 210));
        hapus1.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        hapus1.setForeground(new java.awt.Color(241, 246, 245));
        hapus1.setText("CLEAR");
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(75, 86, 210));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel7)
                                .addGap(115, 115, 115)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator5)
                                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelKryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKryMouseClicked
        txtId.setText(tabelKry.getValueAt(tabelKry.getSelectedRow(),1).toString());
        txtNama.setText(tabelKry.getValueAt(tabelKry.getSelectedRow(),2).toString());
        bagian.setSelectedItem(tabelKry.getValueAt(tabelKry.getSelectedRow(), 3).toString());
        txtNotelp.setText(tabelKry.getValueAt(tabelKry.getSelectedRow(),4).toString());
        jk.setSelectedItem(tabelKry.getValueAt(tabelKry.getSelectedRow(),5).toString());
        txtTgl.setText(tabelKry.getValueAt(tabelKry.getSelectedRow(),6).toString());
        txtAlamat.setText(tabelKry.getValueAt(tabelKry.getSelectedRow(),7).toString());
        
        txtId.setEditable(false);
        simpan.setText("UBAH");
    }//GEN-LAST:event_tabelKryMouseClicked

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        cariData();
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            simpan.doClick();
//            
        }
    }//GEN-LAST:event_txtAlamatKeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        bersih();
        autoNumber();
    }//GEN-LAST:event_batalActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed

        try {
            st = con.createStatement();
            if (txtId.getText().equals("")||
                txtNama.getText().equals("")||
                bagian.getSelectedItem().equals("")||
                txtNotelp.getText().equals("")||
                txtAlamat.getText().equals("")||
                txtTgl.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong","Validasi Data",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (simpan.getText() == "SIMPAN"){
                String cek = "SELECT * FROM karyawan WHERE Id = '"+ txtId.getText() +"'";
                rs = st.executeQuery(cek);
                if (rs.next()){
                    JOptionPane.showMessageDialog(null,"Ups Id ini Sudah Ada");
                } else {
                    String sql = "INSERT INTO karyawan VALUES ('"+ txtId.getText() +
                    "','" + txtNama.getText() +
                    "','" + bagian.getSelectedItem() +
                    "','" + txtNotelp.getText() +
                    "','" + jk.getSelectedItem()+
                    "','" + txtTgl.getText() +
                    "','" + txtAlamat.getText() + "')";
                    //                    String sql2 = "INSERT IGNORE INTO gaji_kry (Id, nama) VALUES ('"+ txtId.getText() +
                    //                            "','" + txtNama.getText() + "')";
                    st.executeUpdate(sql);
                    //                    st.executeUpdate(sql2);
                    JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                    bersih();
                }
            } else {
                String update = "UPDATE karyawan SET nama = '"+ txtNama.getText() +
                "', bagian = '"+ bagian.getSelectedItem() +
                "', telepon = '"+ txtNotelp.getText() +
                "', alamat = '"+ txtAlamat.getText() +
                "' WHERE Id = '"+ txtId.getText() + "'";
                //                String update2 = "UPDATE gaji_kry SET nama = '"+ txtNama.getText() +
                //                        "' WHERE Id = '"+ txtId.getText() +"'";
                st.executeUpdate(update);
                //                st.executeUpdate(update2);
                JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                bersih();
                tampilData()
                ;            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        tampilData();
        autoNumber();
    }//GEN-LAST:event_simpanActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        DefaultTableModel mdl = new DefaultTableModel();
        int jawab = JOptionPane.showConfirmDialog(null,"Semua Data Karyawan Akan Dihapus, Lanjutkan ?","Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (jawab == 0) {
            try {
                st = con.createStatement();
                String sql = "DELETE FROM karyawan";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Semua Data Berhasil Dihapus");
                ((DefaultTableModel)tabelKry.getModel()).setNumRows(0);
                bersih();
                autoNumber();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_hapus1ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        if (txtNama.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Akan Dihapus !");
        } else {
            int jawab = JOptionPane.showConfirmDialog(null,"Data Ini Akan Dihapus, Lanjutkan ?","Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (jawab == 0) {
                try {
                    st = con.createStatement();
                    String sql = "DELETE FROM karyawan WHERE Id = '"+ txtId.getText() + "'";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
                    tampilData();
                    bersih();
                    autoNumber();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        home homi = new home();
        homi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void bagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bagianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bagian;
    private javax.swing.JButton batal;
    private javax.swing.JButton btnTgl;
    private javax.swing.JComboBox<String> cari;
    private cambodia.raven.DateChooser dateChooser1;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hapus1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> jk;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelKry;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNotelp;
    private javax.swing.JTextField txtTgl;
    // End of variables declaration//GEN-END:variables
private void autoNumber() {
    try {
        String sql = "SELECT MAX(RIGHT(Id,3)) AS no_auto FROM karyawan";
        st = con.createStatement();
        rs = st.executeQuery(sql);
        
        if (rs.next()) {
            String no_auto, nol_plus;
            int p;
            nol_plus = "";
            
            no_auto = Integer.toString(rs.getInt(1)+ 1);
            p = no_auto.length();
            for(int i=1;i<=3-p;i++) {
                nol_plus = nol_plus + 0;
            }
            
            txtId.setText("RJ"+ nol_plus + no_auto);
            
        } 
    } catch (Exception e) {
            txtId.setText("RJ001");

    }
}
}
